// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4xHuAG5HlhvMZknElOMITcw9rGn0vRZk',
    appId: '1:851284261736:web:c5b8516dfd87baad68b4dd',
    messagingSenderId: '851284261736',
    projectId: 'main-divine-multiservice-3ef9c',
    authDomain: 'main-divine-multiservice-3ef9c.firebaseapp.com',
    storageBucket: 'main-divine-multiservice-3ef9c.firebasestorage.app',
    measurementId: 'G-36FCK7GF9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_yoCL4ClZOpWLC5zk_mSS0MufOYkFp0',
    appId: '1:851284261736:android:d10fe7485cccac6c68b4dd',
    messagingSenderId: '851284261736',
    projectId: 'main-divine-multiservice-3ef9c',
    storageBucket: 'main-divine-multiservice-3ef9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3cfr4tUaopBdsRIdIyNVTbpsTcOoi1A',
    appId: '1:851284261736:ios:6a59d633de48905268b4dd',
    messagingSenderId: '851284261736',
    projectId: 'main-divine-multiservice-3ef9c',
    storageBucket: 'main-divine-multiservice-3ef9c.firebasestorage.app',
    iosBundleId: 'com.maindivine.mainDivineMultiservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt3cfr4tUaopBdsRIdIyNVTbpsTcOoi1A',
    appId: '1:851284261736:ios:6a59d633de48905268b4dd',
    messagingSenderId: '851284261736',
    projectId: 'main-divine-multiservice-3ef9c',
    storageBucket: 'main-divine-multiservice-3ef9c.firebasestorage.app',
    iosBundleId: 'com.maindivine.mainDivineMultiservices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4xHuAG5HlhvMZknElOMITcw9rGn0vRZk',
    appId: '1:851284261736:web:657a4fecc297f51468b4dd',
    messagingSenderId: '851284261736',
    projectId: 'main-divine-multiservice-3ef9c',
    authDomain: 'main-divine-multiservice-3ef9c.firebaseapp.com',
    storageBucket: 'main-divine-multiservice-3ef9c.firebasestorage.app',
    measurementId: 'G-FTYCFDN52E',
  );
}
